// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPiX1I2lin2apwNkiqkO2VC1W2UHUW6mA',
    appId: '1:1015158869087:web:f4d2517d6027e0b5cf9fea',
    messagingSenderId: '1015158869087',
    projectId: 'newsapp-5f9b3',
    authDomain: 'newsapp-5f9b3.firebaseapp.com',
    storageBucket: 'newsapp-5f9b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpAdHTWJE_elEuH03dhss6KWJGgx3Kd1w',
    appId: '1:1015158869087:android:94058190fab579ebcf9fea',
    messagingSenderId: '1015158869087',
    projectId: 'newsapp-5f9b3',
    storageBucket: 'newsapp-5f9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAMk5BryCbDvoLdNYEisNWTJfszUKVtDU',
    appId: '1:1015158869087:ios:3c614850f0c91f6ccf9fea',
    messagingSenderId: '1015158869087',
    projectId: 'newsapp-5f9b3',
    storageBucket: 'newsapp-5f9b3.appspot.com',
    iosClientId: '1015158869087-bpj6crcg1jj5el9be4ls6thf6t9pqo5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAMk5BryCbDvoLdNYEisNWTJfszUKVtDU',
    appId: '1:1015158869087:ios:55ad6c81c5dfe953cf9fea',
    messagingSenderId: '1015158869087',
    projectId: 'newsapp-5f9b3',
    storageBucket: 'newsapp-5f9b3.appspot.com',
    iosClientId: '1015158869087-ip71gnmctmp9ucrqk0cc1i58j7aramhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesspace.RunnerTests',
  );
}
